### obtener todos los vehicles
get http://localhost:3000/api/vehicles


### obtener un vehicle

get http://localhost:3000/api/vehicles/a02b91bc-3769-4221-beb1-d7a3aeba7dad

### crear un vehicle
post http://localhost:3000/api/vehicles
Content-Type: application/json

{
  "patente" : " AD-736-RT ",

  "marca" : " Honda " 
  
}  



### borrar un recurso
delete http://localhost:3000/api/vehicles/5



### modficar un recurso

PUT http://localhost:3000/api/vehicles/5
Content-Type: application/json


{
  "patente" : " AG-584-AA ",

  "marca" : " Toyota " 
  
}  

### modficar un recurso

patch http://localhost:3000/api/vehicles/2
Content-Type: application/json


{
  "patente" : " AG-584-AB ",

  "marca" : " Toyota " 
  
}  
